# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide
description: "My eval"

prompts:
  - file://prompts/eliciting_narrative_thread.txt
  

providers:
  - "openai:gpt-4o-mini"
  

tests:
  # Load transcripts from external files
  - vars:
      case2: file://transcripts/case4.txt
    assert:
      - type: is-json
      - type: answer-relevance
      - type: model-graded-closedqa
        value: The model should not evaluate too harshly or look for "deep" exploration. 
      - type: model-graded-closedqa
        value: If Q&A is mentioned, the model should give the score corresponding to Q&A (2). Otherwise, the score should not be a 2.